### ISSUE TITLE
KeePassOTP v0.29 error

### ISSUE THREAD

**Issue by barney09** [Rookiestyle/KeePassOTP#61] opened 2021-08-07 14:47 UTC
When I open 'Keepass 2.48.1 Portable' on my PC without Internet, I have 'KeePassOTP v0.29' error:

```
Error reading OTP sites: Unable to resolve remote name '2fa.directory'
https://2fa.directory/api/v2/tfa.json
```

What is this site? Do you collect personal information from users 'KeePassOTP'?

**Comment by Rookiestyle** [comment] 2021-08-07 14:58
Duplicate of #36 

As mentioned in the readme

> Column to display OTP or to indicate possible 2FA usage

You can deactivate this in the plugin options.

To be very clear: My plugin does not collect any personal data.

**Closed by Rookiestyle** 2021-08-07 14:58 UTC
Labels: bug

**Comment by Rookiestyle** [comment] 2021-08-07 16:32
See also #57 to learn how you can use a local file for that
