### ISSUE TITLE
Database KeePassOTP not open after update kepass to 2.50 and update KeePassOTP plugin to 1.2

### ISSUE THREAD

**Issue by M-IA** [Rookiestyle/KeePassOTP#89] opened 2022-01-13 09:19 UTC
After update kepass to 2.50 and update KeePassOTP plugin to 1.2  Database KeePassOTP (password and key) open only once.
The otp database does not open. Password and key does not match

**Comment by Rookiestyle** [comment] 2022-01-13 12:42
So you're saying your main database can be opened but when you enter the password and keyfile for the embedded otp database, these credentials are not accepted?
Please attach a screenshot off the otp database unlock window and a debug file (see the wiki) and try answering below questions.

Does it work with KeePass 2.50 and the previous KeePassOTP release?

Does it work with KeePass 2.49 and the previous KeePassOTP release?

Does it work with KeePass 2.49 and the current KeePassOTP release?

**Comment by M-IA** [comment] 2022-01-13 16:18
So you're saying your main database can be opened but when you enter the password and keyfile for the embedded otp database, these credentials are not accepted? **Yes**
Please attach a screenshot off the otp database unlock window and a debug file (see the wiki) and try answering below questions. **OK**
[Debug_KeePassOTP.zip](https://github.com/Rookiestyle/KeePassOTP/files/7864193/Debug_KeePassOTP.zip)

![2022-01-13 19_01_49-Open OTP database - pass kdbx](https://user-images.githubusercontent.com/97666063/149367072-b5dd4310-32aa-45d6-bfbd-28e788728b33.png)
![2022-01-13 19_01_00-Open OTP database - pass kdbx](https://user-images.githubusercontent.com/97666063/149367086-72aa386b-09f4-475b-b1a0-5496782f22e8.png)

**Database OTP Now** 

Does it work with KeePass 2.50 and the previous KeePassOTP release? **No**

Does it work with KeePass 2.49 and the previous KeePassOTP release? **No**

Does it work with KeePass 2.49 and the current KeePassOTP release? **No**

**Database main and OTP before the update KeePass 2.50**

Does it work with KeePass 2.49 and the previous KeePassOTP release? **Yes**

Does it work with KeePass 2.49 and the current KeePassOTP release? **Yes**

I also tried to synchronize the main database after updating keepass to 2.50 with the archived version of the database. The main database does not open with OTP. The database opens, the OTP does not open.

The archived copy of the database has earned in a bundle: Keepass 2.50 with Keepass OTP 1.2, Keepass 2.50 with Keepass OTP 1.12, Keepass 2.49 with Keepass OTP 1.2, Keepass 2.49 with Keepass OTP 1.12.
After saving, the database no longer opens in the OTP part.

Now, after all the manipulations, I am inclined to believe that the database in the OTP part may be broken by keepass 2.50 itself. Before the update, there were no such problems. Because after saving, the master key and the key file do not fit to the OTP
![2022-01-13 18_02_13-KeePassOTP](https://user-images.githubusercontent.com/97666063/149367096-749e2190-42b7-4d42-abd7-ac031e83e756.png)
![2022-01-13 18_01_21-KeePassOTP](https://user-images.githubusercontent.com/97666063/149367101-a1025c29-70f8-48b5-92cb-d031229669d3.png)

**Comment by Rookiestyle** [comment] 2022-01-13 16:32
Thanks for the swift response. I'll do some investigations

**Comment by M-IA** [comment] 2022-01-14 07:51
update: When you download the attachment in the backup entry and.save it as kdbx file, can you open it? **Yes**

**Comment by M-IA** [comment] 2022-01-14 07:55
main database (non in the backup) first open in KeePass 2.50 Keepass OTP 1.2 , Sava as - NO

**Comment by Rookiestyle** [comment] 2022-01-14 09:55
> main database (non in the backup) first open in KeePass 2.50 Keepass OTP 1.2 , Sava as - NO

I don't understand sorry.

I tried the following:
Create new database including embedded OTP database with Keepers 2.49 and KeePassOTP 1.1.2
OTP database is protected with empty password and keyhole, like in your screenshot

I can open everything without issues and all combinations KeePass 2.49 / 2.50 and KeePassOTP 1.1.2 / 1.2  

As I can't reproduce the issue and I did not change the way of opening a database and KeePass did not change it either I'm a bit lost.

If my understanding is correct, you do have a working backup of your main db (and otp th).
If you copy it (to not tamper your backup), with which combinations can you open it.

**Comment by M-IA** [comment] 2022-01-14 16:58
Initially (before any updates and before attempts to reproduce the problem again) there was a version of kepass 2.49 and opt 1.12, in which everything was opened from the main database (not from a backup).
Then the kepass version was updated to version 2.50, otp was version 1.12. Otp was not used (because there was UAC mode).
Then came the otp update to 1.2.
Further, the main base opened once, including OTP.
After opening asked to save.
After the base in Otp was no longer opened. Let's call it the broken main base.
I don't know what exactly broke the OTP database - kepass or kepass OTP.

But it is no longer opened by OTP in any version.

Now I also cannot reproduce this problem using the database from the backup.
Those. the main base from a backup is covered by all versions.

Now: if I synchronize a broken database (OTP) with a database from a backup, the OTP database no longer opens in the database from the backup.

At the moment, this is the only way to make sure that the database from the backup is no longer opened.

**Comment by Rookiestyle** [comment] 2022-01-17 18:23
So you're saying currently everything works and you can only reproduce the issue when you synchronize a working database including OTP with a newer databse inclodung boken otp database?

If that's the case, I'll close this ticket.


Additionally, I'm working on feature to import an OTP database which might make a "restore from backup" easier

**Closed by Rookiestyle** 2022-01-17 18:23 UTC
Labels: bug, more information required
