### ISSUE TITLE
Extend Setup by Screenshot feature

### ISSUE THREAD

**Issue by An-dir** [Rookiestyle/KeePassOTP#54] opened 2021-05-05 15:18 UTC
## Summary
Add a screenshot feature to the setup if the new QRCode is not draggable or not compatible.
![image](https://user-images.githubusercontent.com/11379014/117152604-785fd200-adba-11eb-8bd8-a8b5c7f3f9d3.png)

## Added value
- Allows any displayed qrcode image to be imported (unknown/wrong file extension; generated svg qrcodes)
- Allows not draggable images to be imported

## Example
In my case i had a 150x150px 24Bit PNG file wich did nothing after drag and drop. So i had to make a screenshot save it and then make drag and drop. After some more research i found the issue that the *.png named file originally is a jpeg file, so downloading, renaming and then drag&drop works.

Microsoft generated me the "PNG" (in fact jpg) file in a testing environment - Drag&Drop won't work:
![My Sign-Ins - Downloaded](https://user-images.githubusercontent.com/11379014/117164718-2ec8b480-adc5-11eb-95b5-bb045b17c1d9.png)

**Comment by Rookiestyle** [comment] 2021-05-05 18:15
Taking a screenshot would require quite some change to the plugin (multi-monitors, search QR code within a screenshot, ...) and it would need to minimize KeePass to ensure that KeePass does not hide the QR code

I would rather analyze why it failed to work in your case.
The QR code linked in your issue can be drag'dropped.

Please let me know how to reproduce this.

**Comment by An-dir** [comment] 2021-05-06 09:44
I am a bit confused. While yesterday i was able to reproduce the error multiple times no matter what i tried nothing worked - today everything is fine. so drag&drop works fine.

anyway it might be helpful to be able to copy paste a screenshot made by snipping tool etc. without having to save it fist.

for me everything is fine now.

thank you for your quick reply.

**Comment by hauk92** [comment] 2021-05-18 16:17
Another example of a non dragable QR code is on GitHub itself (https://github.com/settings/two_factor_authentication/intro or https://github.com/settings/two_factor_authentication/verify respectively) or https://tutanota.com/.
For tutanota you can register a free account on https://mail.tutanota.com/signup and setup 2fa on https://mail.tutanota.com/settings/login.

**Comment by Rookiestyle** [comment] 2021-05-18 16:29
**Bad news**
I can't drag & drop on tutonata either.
Since it's not the dropping but the dragging that's not possible, I can't do anything about it as neither KeePass nor KeePassOTP is involved here

**Good news**
The next version of KeePassOTP which will be released soon, will allow screen capture it it will find and read the OTP qr code shown in tutanota

**Comment by hauk92** [comment] 2021-05-18 17:06
Thank you!

**Closed** 2021-05-18 19:09 UTC
Labels: enhancement
