### ISSUE TITLE
OTP setup menu size is smaller than the space its controls occupy, hence making it overflow and cut the excessive controls

### ISSUE THREAD

**Issue by MutexMorgan** [Rookiestyle/KeePassOTP#63] opened 2021-08-18 04:35 UTC
## Overview
[Imgur screenshot](https://i.imgur.com/Ft5Z9yd.png)

## Steps to Reproduce
1. Use 1366x766 resolution display
2. Create an entry
3. Open the OTP menu of the entry

## Expected Behavior
The OTP setup menu is expected to properly show controls.

## Actual Behavior
OTP setup menu size is smaller than the space its controls occupy inside it, hence making it overflow and cut the excessive controls

## Context
OS:  Win 10 Home Version 2004, Build 19041.1165
KeePass Version: 2.48.1
Plugin Version: 0.29(also 0.28, since the display QR code scan features was added)

**Comment by Rookiestyle** [comment] 2021-08-18 04:43
Will need to test this, thanks for letting me know.

Does it show the full window if you tick *use advanced options*?

**Comment by MutexMorgan** [comment] 2021-08-18 05:37
[Nope](https://i.imgur.com/1YBdkUG.png)

**Comment by MutexMorgan** [comment] 2021-08-18 05:40
Also removed all other plugins and tested, the results are the same
[Pic1](https://i.imgur.com/8gtg4IJ.png) [Pic2](https://i.imgur.com/StPzIh0.png)

**Comment by Rookiestyle** [comment] 2021-08-18 06:08
I changed the resolution of my screen to 1366 x 768 (I guess 1366 x 76**6** is just a type?) and tried with both font scaling 100% and 125%.
I can't reproduce the issue.

Is my understanding correct: 0.27 did not show this issue?

I need to further investigate, might take some time due to not being able to reproduce the issue.

**Comment by MutexMorgan** [comment] 2021-08-18 06:20
Yeah, it's 1366 x 768, mistyped it

And yeah, 0.27 didn't show it

**Comment by Rookiestyle** [comment] 2021-08-18 12:21
I found a way to reproduce this and afterwards fixed in. My tests were successful.
Please try the attached version and let me know the result.
It will identify as 0.29.1 and the only change is in the layout of the UI elements

If it's working for you as well, I will include in the next release which will be available soon.

[KeePassOTP.zip](https://github.com/Rookiestyle/KeePassOTP/files/7007117/KeePassOTP.zip)

**Comment by MutexMorgan** [comment] 2021-08-18 17:03
Yes it displays correctly now!
[Pic1](https://i.imgur.com/8xBgHzh.png) [Pic2](https://i.imgur.com/CzZe1cX.png)

Thank you!

**Closed** 2021-08-19 13:29 UTC
Labels: bug
