### ISSUE TITLE
KeePassOTP and KPEnhancedEntryView

### ISSUE THREAD

**Issue by caspadan** [Rookiestyle/KeePassOTP#138] opened 2023-06-17 07:34 UTC
## Overview
1. Read OTP QR code from screen function does not drop KeePass window to background when using KPEnhancedEntryView plugin.
2. Also, I've noticed the OTP setup window seems a little unresponsive (even without KPEnhancedEntryView plugin).  You have to wait a bit for the window to close when clicking cancel.  This might be the case after moving to KeePass 2.54, but haven't tested in 2.53.1.

Please note, I tested with KeePassOTP plugin on it's own and added one plugin at at time and as soon as I had KPEnhancedEntryView, the problem arouse. I put all my other plugins in (excluding KPEnhancedEntryView), and it worked just as it did with only KeePassOTP. 

*Did not test the Drag & Drop function

I am aware, this may not be a problem with your plugin.

## Steps to Reproduce
First make sure to have KeePassOTP and KPEnhancedEntryView plugins loaded in KeePass.
1.  Right click an entry, and choose KeePassOTP > OTP setup... (put in OTP database password if you save to a separate database and that database is not yet open)
2.  Click "Read OTP QR code from screen"

## Expected Behavior
KeePass window is supposed to drop to the background to be able to read a QR code.

## Actual Behavior
Nothing happens, and KeePass stays in foreground.

## Context
OS:  Win 11
KeePass Version: 2.54
Plugin Version: 1.6.5
KPEnhancedEntryView plugin Version: 2.5.0
[Debug_KeePassOTP_20230617T072349Z.xml.log](https://github.com/Rookiestyle/KeePassOTP/files/11778231/Debug_KeePassOTP_20230617T072349Z.xml.log)

**Comment by Rookiestyle** [comment] 2023-06-17 08:53
> Read OTP QR code from screen function does not drop KeePass window to background when using KPEnhancedEntryView plugin.

I can fix that


> Also, I've noticed the OTP setup window seems a little unresponsive (even without KPEnhancedEntryView plugin). You have to wait a bit for the window to close when clicking cancel.

I can't reproduce that.
When closing the OTP setup window (Cancel, "X", Esc key), I don't experience any delay.
Only thing I can imagine is when trying to read an OTP QR code from screen. The intended behaviour is:
1. Drop to background
2. Search for OTP QR code on the screen
3. Bring KeePass to foreground **EITHER** if QR code was found and parse QR code **OR** after 30 seconds

While 2) is running and neither a QR code was found nor the 30 seconds timeout is reached, the OTP setup window stays open.
If you refer to something different, I need more details.

**Comment by caspadan** [comment] 2023-06-17 08:56
Thanks, I will take a look and let you know if I find anything, but it could just be due to the 30 second timer as you now mentioned.

**Comment by Rookiestyle** [comment] 2023-06-17 09:24
The new release should solve both topics

**Closed** 2023-06-17 09:24 UTC
Labels: bug, more information required
