### ISSUE TITLE
KeePassOTP broke after updating Yandex key v3.0

### ISSUE THREAD

**Issue by rdbox** [Rookiestyle/KeePassOTP#112] opened 2022-10-02 18:15 UTC
## Overview
[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: # (Give a BRIEF summary about your problem)

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. Yandex key updated version 3.0
there is now a different principle of operation.
I want to add keepass and KeePassOTP to my applications, it cannot understand the QR code and the grab grab and transfer mode does not work either
 also lost the ability to add a seed key

## Expected Behavior
[NOTE]: # (Describe how you expect the plugin to behave)

so that the plugin can recognize the QR code and add my password from Yandex key
## Actual Behavior
[NOTE]: # (Describe how the plugin actually behaves)

## Context
[NOTE]: # (Provide any additional information you may have)
OS: android 10
KeePass Version:  2.51.1
Plugin Version: 1.5

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)

**Comment by Rookiestyle** [comment] 2022-10-05 17:59
[KeePassOTP.zip](https://github.com/Rookiestyle/KeePassOTP/files/9717915/KeePassOTP.zip)
Please try with the attached version.

If this does not work, you can try the following
* Instead of scanning th QR code, to switch to display of the the secret 
* Enter the secret as seed in KeePassOTP
* In the Advanced sectoin, switch to Yandex (should be TOTP) and enter you PIN length

**Comment by rdbox** [comment] 2022-10-06 07:42
@Rookiestyle I checked the version from the archive.
Unfortunately, it does not help, does not work.

**here is this QR code (for demonstration purposes)**
![image](https://user-images.githubusercontent.com/18515862/194246728-15c117d9-0223-413d-8202-8668f77fc526.png)

The problem is that when I click the button
Read OTP and switch to the window with the QR code, the plugin seems to be frozen and does not react in any way.
The plug-in, I would call it frozen, is frozen and after 10 seconds it is defrosted


The seed code does not work either, the seed code is added to the keepassOTP plugin successfully, but the problem is that the temporary codes are not correct, they differ from those that I have in my phone with the Yandex key application. I thought there was no time synchronization problem, added the seed code to the keepassOTP application and saved it as such. Time codes are not synchronized with the Yandex key application in the phone.

I think the developers of the Yandex service have changed the settings and something needs to be fixed somewhere in the plugin.
Set up magic to work perfectly

I tried to explain the problem correctly, I hope you understand me)))

**Comment by Rookiestyle** [comment] 2022-10-08 07:19
I do experience similar issues and the Yandex app on my smartphone cannot even scan above screenshot - the QR code that is shown to me when I try to enroll for 2FA.

When I do "Follow the link" and follow all steps, I can setup everything in both, the Yandex key app and KeePassOTP.
The codes are off but in my tests both are accepted. I guess because they are not actually off but out of sync.
The one generated by KeePassOTP does not work for you?

> I think the developers of the Yandex service have changed the settings and something needs to be fixed somewhere in the plugin

Yes, of course :) Something was changed.
The main difficulty is, that Yandex 2FA uses a proprietary algorithm that is not published and therefor the implementation is unknown. If this was changed and they publish their algorithm it would be easy to implement it.
As long as this is not the case, it will be cumbersome and errorprone.
I'll continue trying but there is no guarantee.

**Comment by rdbox** [comment] 2022-10-08 08:16
> The one generated by KeePassOTP does not work for you?

Thanks. No, it doesn't work, it says that the error is an invalid temporary code.
And in the Yandex application, the key code is correct, which is scanned via a QR code.


The screenshot that I sent above, I scan it into the Yandex key application and then my authorized Yandex account is shown in the same application, like this is how it works.
When I scanned through the QR code, 2 Yandex key functions appear, I can log into my account by entering a temporary code, or I can log in through the QR scan when in the authorization itself on the Yandex site

**Comment by Rookiestyle** [comment] 2022-10-10 08:22
I'm a bit lost here.
Let me explain what I did and please let me know what you do different

1. Created a new account at Yandex
2. Start setup of 2FA at Yandex
3. As my Yandex.Key app does not let me scan the QR code shown during this setup, I click "follow the link"
4. Confirm my mobile number
5. Enter the one time code sent as SMS
6. Scan the QR code to setup 2FA - This should work with the attached debug version of KeePassOTP 1.5.0.2
7. Navigate to the "Use advanced options" and enter the PIN
8. Codes like *edrkkvlu* are created
9. Enter one time password as last step of 2fa setup to verify the setup
10. Setup completed
11. Login again to e. g. mail.yandex.ru
12. Enter one time password
13. Login successful

If you do something different, let me know where and what you're doing different?
Which version of the Yandex.Key app do you use?
Did you check your computer's time? If it's off you can go "Use advanced options" and compensate it

[KeePassOTP.zip](https://github.com/Rookiestyle/KeePassOTP/files/9744272/KeePassOTP.zip)

**Comment by Rookiestyle** [comment] 2022-10-10 09:59
I enrolled to the beta program and now have Yandex.Key app version v3.0.1 installed.

I am forced to login to the app using username and password, no chance to scan anything.
Once logged in in Yandex.Key, I also don't have a way to extract the secret that is required to generate the codes anywhere else outside the app.

I close this issue, Yandex support of KeePassOTP is not possible with versions >= 3 unfortunately.

If you can share implementation details or if Yandex will publish it, I will reopen this issue and add it to my plugin as well

**Closed by Rookiestyle** 2022-10-10 09:59 UTC
Labels: enhancement, more information required

**Comment by dartraiden** [comment] 2022-11-20 17:32
You still can use v2 sheme.

1) Login to https://id.yandex.ru (2FA is supposed to be disabled)
2) Go to https://id.yandex.ru/security and enable Yandex.Key
3) Choose "I use an app < 3.0"
<img width="277" alt="firefox_0NWkgjdT0i" src="https://user-images.githubusercontent.com/5046855/202916826-a2b1f94b-b986-4f11-9978-cca613788f0e.png">
4) You will be asked to verify your phone number, then you will receive an QR code which you can import

**Comment by f1h0** [comment] 2022-11-21 05:53
@dartraiden 
thanks i will try this way

**Comment by f1h0** [comment] 2023-02-24 13:42
the problem is in this approach, it is impossible to combine the Yandex key version 3.0 on the phone and the version of keepassOTP that is below < 3.0 there is a conflict, this is a problem.

need to update KeepasOTP support

**Comment by dartraiden** [comment] 2023-02-24 13:52
> Yandex key version 3.0 on the phone

You can use Aegis instead. It supports Yandex TOTP < 3.0

**Comment by Rookiestyle** [comment] 2023-02-24 13:54
Yandex algorithm is not public.
If the algorithm will be published, it is possible to update KeePassOTP.
If the algorithm will not be published, an update of KeePassOTP is not possible.
